### ISSUE TITLE
🎉 Story 1: Initialize the Next.js Project

### ISSUE THREAD

**Issue by bshongwe** [bshongwe/rate-my-professor-ai-assistant#1]

**Comment by bshongwe** [comment]
**Tasks:**

- [ ]     🛠️ Initialize Next.js with TypeScript.
- [ ]     🎨 Install Material-UI.
- [ ]     🧹 Configure ESLint and Prettier for code quality

**Comment by bshongwe** [comment]
🌟 Epic: Set Up Project Infrastructure
