### ISSUE TITLE
🔒 Story 2: Configure Environment Variables

### ISSUE THREAD

**Issue by bshongwe** [bshongwe/rate-my-professor-ai-assistant#2]

**Comment by bshongwe** [comment]
**Tasks:**

- [ ]     🗒️ Create a .env file.
- [ ]     📚 Document required environment variables.
- [ ]     🔐 Ensure sensitive information is secured.

**Comment by bshongwe** [comment]
🌟 Epic: Set Up Project Infrastructure
