### ISSUE TITLE
💬 Story 7 - Create Chat Interface: Develop the chat interface using Material-UI components

### ISSUE THREAD

**Issue by bshongwe** [bshongwe/rate-my-professor-ai-assistant#7]

**Comment by bshongwe** [comment]
**Tasks:**

- [ ]     🖥️ Design the chat layout using Material-UI.
- [ ]     📝 Implement user input handling.
- [ ]     🗨️ Display AI assistant responses in the chat interface.

**Comment by bshongwe** [comment]
🎨 Epic: Develop the Frontend UI
